name: CI Placeholder

on:
  push:
    branches: [daddy]
  pull_request:
    branches: [daddy]

jobs:
  placeholder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hi 👋
        run: echo "GitHub Actions is working! 🚀"
